Description: "Cloud Formation Template to set up HQU Code Pipeline for Lambda functions"
Parameters: 
  DatabaseHost: 
    NoEcho: true
    Description: Database host to which Lambda functions connect
    Type: String
  DatabaseUser: 
    NoEcho: true
    Description: Used by the Lambda functions to connect to the database
    Type: String
    MinLength: 1
    MaxLength: 16
    AllowedPattern: "[a-zA-Z][a-zA-Z0-9]*"
    ConstraintDescription: must begin with a letter and contain only alphanumeric characters.
  DatabasePassword: 
    NoEcho: true
    Description: Used by the Lambda functions to connect to the database
    Type: String
    MinLength: 1
    MaxLength: 41
    AllowedPattern: "[a-zA-Z0-9]*"
    ConstraintDescription: must contain only alphanumeric characters.
  DatabaseDBName: 
    NoEcho: true
    Description: Database accessed by the Lambda functions
    Type: String
    MinLength: 1
    MaxLength: 16
    AllowedPattern: "[a-zA-Z][a-zA-Z0-9]*"
    ConstraintDescription: must begin with a letter and contain only alphanumeric characters.
  DatabaseVPC: 
    Description: VPC of the Database instance
    Type: "List<AWS::EC2::VPC::Id>"
  DatabaseSubnet1: 
    Description: Subnet of database instance
    Type: "List<AWS::EC2::Subnet::Id>"
  DatabaseSubnet2: 
    Description: Subnet of database instance
    Type: "List<AWS::EC2::Subnet::Id>"
  DatabaseSecurityGroup: 
    Description: Security group of database instance
    Type: "List<AWS::EC2::SecurityGroup::Id>"
Resources:
  CodeBuildBucket:
    Type: AWS::S3::Bucket
    Properties:
      Name: !Sub ${AWS::StackName}-artifacts
  CodeBuildRole:
    Type: AWS::IAM::Role 
    Properties: 
      AssumeRolePolicyDocument: 
        Statement: 
          -
            Action:
              - "sts:AssumeRole"
            Effect: "Allow"
            Principal: 
              Service: "codebuild.amazonaws.com"
            Version: "2012-10-17"
  LambdaExecutionRole:
    Type: AWS::IAM::Role 
    Properties: 
      AssumeRolePolicyDocument: 
        Statement: 
          -
            Action:
              - "sts:AssumeRole"
            Effect: "Allow"
            Principal: 
              Service: "lambda.amazonaws.com"
            Version: "2012-10-17"
  CodeBuildProject:
    Type: AWS::CodeBuild::Project
    Properties: 
      Name: !Sub ${AWS::StackName}-codebuild-project
      Description : 'Building the Lambda function zip files and putting them into the S3 bucket'
      ServiceRole: !Ref CodeBuildRole
      Source:
        Type: 'CODEPIPELINE'
        BuildSpec: 
          !Sub |
          version: 0.2
          phases:
            install:
              commands:
                - sudo apt-get update
                - sudo apt-get --assume-yes install libmysqlclient18
                - sudo apt-get --assume-yes install python3-pip
                - sudo pip3 install 'mysql_connector_python<8.1' -t .
                - sed -i 's/_DATABASE_HOST/${DatabaseHost}/g' samTemplate.yaml
                - sed -i 's/_DATABASE_USER/${DatabaseUser}/g' samTemplate.yaml
                - sed -i 's/_DATABASE_PASSWORD/${DatabasePassword}/g' samTemplate.yaml
                - sed -i 's/_DATABASE_DB_NAME/${DatabaseDBName}/g' samTemplate.yaml
                - sed -i 's/_DATABASE_SUBNET_1/${DatabaseSubnet1}/g' samTemplate.yaml
                - sed -i 's/_DATABASE_SUBNET_2/${DatabaseSubnet2}/g' samTemplate.yaml
                - sed -i 's/_DATABASE_SECURITY_GROUP/${DatabaseSecurityGroup}/g' samTemplate.yaml
                - aws cloudformation package --template-file samTemplate.yaml --s3-bucket ${StaticBucket} --output-template-file outputSamTemplate.yaml                         
            artifacts:
              type: zip
                files:
                  - samTemplate.yaml
                  - outputSamTemplate.yaml
      Environment:
        Type: 'LINUX_CONTAINER'
        ComputeType: 'BUILD_GENERAL1_SMALL'
        Image: 'aws/codebuild/ubuntu-base:14.04'
      Artifacts:
        Type: 'CODEPIPELINE'
      TimeoutInMinutes: 10
    
  CodePipelineProject:
    Type: AWS::CodePipeline::Pipeline
    Properties:
      RoleArn: arn:aws:iam::187231954982:role/AWS-CodePipeline-Service
      ArtifactStore: 
        Type: S3 
        Location: !Ref CodeBuildBucket
      Stages:
        -
          Name: Source
          Actions:
            - 
              Name: SourceAction 
              ActionTypeId:
                Category: Source 
                Owner: ThirdParty
                Version: 1
                Provider: GitHub
              OutputArtifacts:
                Name: SourceOutput
              Configuration:
                Owner: 'matthew-trump'
                Repo: 'hqu-trivia-api-backend'
                Branch: 'master'
                OAuthToken: 'c4a3523184478b2d51ba89d8c70551fbcf062fac'
              RunOrder: 1
        - 
          Name: Build 
          Actions: 
            - 
              Name: BuildAction 
              ActionTypeId: 
                Category: Build 
                Owner: AWS 
                Version: 1
                Provider: CodeBuild
              InputArtifacts:
                Name: SourceOutput 
              OutputArtifacts:
                Name: BuildOutput
              Configuration:
                ProjectName: !Ref CodeBuildProject
              RunOrder: 1 
        - 
          Name: Staging 
          Actions: 
            - 
              Name: StagingAction 
              ActionTypeId:
                Category: Deploy 
                Owner: AWS
                Version: 1
                Provider: CloudFormation 
              Configuration:
                ActionMode: 'CHANGE_SET_REPLACE'
                StackName: !Sub ${AWS::StackName}-Lambda-Stack
                ChangeSetName: !Sub ${AWS::StackName}-Lambda-ChangeSet
                RoleArn: !GetAtt 'LambdaExecutionRole.Arn'
                Capabilities: 'CAPABILITY_IAM'
                TemplatePath: BuildOutput::outputSamTemplate.yaml
              RunOrder: 1
        - 
          Name: Deploy 
          Actions:
            - 
              Name: DeployAction 
              ActionTypeId:
                Category: Deploy
                Owner: AWS 
                Version: 1
                Provider: CloudFormation 
              Configuration: 
                ActionMode: 'CHANGE_SET_EXECUTE'
                StackName: !Sub ${AWS::StackName}-Lambda-Stack
                ChangeSetName: !Sub ${AWS::StackName}-Lambda-ChangeSet
              RunOrder: 1
      
      
